services:

  db:
    image: postgres:16-alpine
    container_name: nut_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nut_user
      POSTGRES_PASSWORD: nut_password
      POSTGRES_DB: nut_dev
    volumes:
      - nut_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
      image: dpage/pgadmin4
      container_name: nut_pgadmin
      restart: unless-stopped
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@nut.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - db

  api:
    build:
      context: ./backend
    container_name: nut_api
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  nut_db_data: