"""add_quality_fields_and_quality_check_table

Revision ID: 081c7b03de6b
Revises: 415736039031
Create Date: 2026-03-31 08:38:58.646888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '081c7b03de6b'
down_revision: Union[str, None] = '415736039031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # qualitycheckresult : créé automatiquement par create_table via sa.Enum
    op.create_table('quality_check',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_container', sa.BigInteger(), nullable=False),
    sa.Column('id_operator', sa.BigInteger(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('result', sa.Enum('apte', 'a_surveiller', 'inapte', name='qualitycheckresult'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_container'], ['container.id'], ),
    sa.ForeignKeyConstraint(['id_operator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('container', sa.Column('id_owner_organization', sa.BigInteger(), nullable=True))
    # ownershiptype : add_column ne crée pas le type automatiquement, on le crée manuellement
    op.execute("CREATE TYPE ownershiptype AS ENUM ('achat', 'location')")
    op.add_column('container', sa.Column('ownership_type', postgresql.ENUM('achat', 'location', name='ownershiptype', create_type=False), nullable=True))
    op.add_column('container', sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('container', sa.Column('first_use_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('container', sa.Column('batch_number', sa.String(length=100), nullable=True))
    op.add_column('container', sa.Column('last_quality_check', sa.DateTime(timezone=True), nullable=True))
    op.add_column('container', sa.Column('quality_check_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'container', 'organization', ['id_owner_organization'], ['id'])
    op.add_column('container_status_history', sa.Column('id_responsible_org', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'container_status_history', 'organization', ['id_responsible_org'], ['id'])
    op.add_column('container_type', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('container_type', sa.Column('temp_min', sa.Integer(), nullable=True))
    op.add_column('container_type', sa.Column('temp_max', sa.Integer(), nullable=True))
    op.add_column('container_type', sa.Column('wash_recommendations', sa.Text(), nullable=True))
    op.add_column('container_type', sa.Column('quality_check_interval', sa.Integer(), nullable=True))
    op.add_column('container_type', sa.Column('id_supplier', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'container_type', 'organization', ['id_supplier'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'container_type', type_='foreignkey')
    op.drop_column('container_type', 'id_supplier')
    op.drop_column('container_type', 'quality_check_interval')
    op.drop_column('container_type', 'wash_recommendations')
    op.drop_column('container_type', 'temp_max')
    op.drop_column('container_type', 'temp_min')
    op.drop_column('container_type', 'color')
    op.drop_constraint(None, 'container_status_history', type_='foreignkey')
    op.drop_column('container_status_history', 'id_responsible_org')
    op.drop_constraint(None, 'container', type_='foreignkey')
    op.drop_column('container', 'quality_check_count')
    op.drop_column('container', 'last_quality_check')
    op.drop_column('container', 'batch_number')
    op.drop_column('container', 'first_use_date')
    op.drop_column('container', 'purchase_price')
    op.drop_column('container', 'ownership_type')
    op.execute("DROP TYPE IF EXISTS ownershiptype")
    op.drop_column('container', 'id_owner_organization')
    # qualitycheckresult : supprimé automatiquement par drop_table via sa.Enum
    op.drop_table('quality_check')
    # ### end Alembic commands ###
