"""add_credit_config

Revision ID: 136739e13be2
Revises: c1beb3f9f3a6
Create Date: 2026-04-07 13:00:04.130846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136739e13be2'
down_revision: Union[str, None] = 'c1beb3f9f3a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_config',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_organization', sa.BigInteger(), nullable=False),
    sa.Column('id_cont_type', sa.BigInteger(), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_cont_type'], ['container_type.id'], ),
    sa.ForeignKeyConstraint(['id_organization'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_organization', 'id_cont_type', name='uq_credit_config_org_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_config')
    # ### end Alembic commands ###
