"""add_reference_tables

Revision ID: 2645cbafa031
Revises: 5e2d5159bf9f
Create Date: 2026-04-16 08:14:22.255718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2645cbafa031'
down_revision: Union[str, None] = '5e2d5159bf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_container_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('order', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ref_event_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ref_order_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ref_place_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ref_stock_status',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ── Seed data ─────────────────────────────────────────────────────
    op.execute("""
        INSERT INTO ref_place_type (code, label) VALUES
        ('restaurant',        'Restaurant'),
        ('cuisine_collective', 'Cuisine collective'),
        ('laveur',            'Laveur'),
        ('entrepot',          'Entrepôt'),
        ('point_collecte',    'Point de collecte'),
        ('centre_commercial', 'Centre commercial'),
        ('camion',            'Camion'),
        ('recycleur',         'Recycleur'),
        ('destructeur',       'Destructeur'),
        ('autre',             'Autre')
    """)
    op.execute("""
        INSERT INTO ref_order_type (code, label) VALUES
        ('lavage',    'Lavage'),
        ('transport', 'Transport'),
        ('contenants','Contenants'),
        ('machine',   'Machine')
    """)
    op.execute("""
        INSERT INTO ref_container_status (code, label, color, "order") VALUES
        ('propre',      'Propre',        '#16A34A', 1),
        ('en_consigne', 'En consigne',   '#3B82F6', 2),
        ('sale',        'Sale',          '#F59E0B', 3),
        ('en_lavage',   'En lavage',     '#8B5CF6', 4),
        ('en_transit',  'En transit',    '#06B6D4', 5),
        ('perdu',       'Perdu',         '#EF4444', 6),
        ('a_detruire',  'À détruire',    '#DC2626', 7),
        ('detruit',     'Détruit',       '#6B7280', 8)
    """)
    op.execute("""
        INSERT INTO ref_stock_status (code, label) VALUES
        ('en_cours',   'En cours'),
        ('ferme',      'Fermé'),
        ('en_transit', 'En transit'),
        ('archive',    'Archivé')
    """)
    op.execute("""
        INSERT INTO ref_event_type (code, label) VALUES
        ('container_scan',           'Scan contenant'),
        ('container_status_change',  'Changement de statut'),
        ('container_created',        'Création contenant'),
        ('credit_gain',              'Gain de crédits'),
        ('credit_depense',           'Dépense de crédits'),
        ('credit_ajustement',        'Ajustement de crédits'),
        ('quality_check',            'Contrôle qualité'),
        ('order_created',            'Création commande'),
        ('order_status_change',      'Changement statut commande')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_stock_status')
    op.drop_table('ref_place_type')
    op.drop_table('ref_order_type')
    op.drop_table('ref_event_type')
    op.drop_table('ref_container_status')
    # ### end Alembic commands ###
