"""add_owner_organization_to_stock

Revision ID: abc05f03ad47
Revises: 081c7b03de6b
Create Date: 2026-03-31 12:37:25.543798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc05f03ad47'
down_revision: Union[str, None] = '081c7b03de6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('id_owner_organization', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'stock', 'organization', ['id_owner_organization'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'id_owner_organization')
    # ### end Alembic commands ###
